spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    show-sql: true

  servlet:
    multipart:
      max-file-size: 8MB
      max-request-size: 8MB

logging:
  config: classpath:log4j2-prd.xml

cors:
  enabled: false
  allowed-origins: '*'