
### Scheme
### List
GET http://localhost:8688/api/v1/schemes
Content-Type: application/json

### Get
GET http://localhost:8688/api/v1/schemes/9
Content-Type: application/json

###
POST http://localhost:8688/api/v1/schemes
Content-Type: application/json

{
    "nameTag": "test",
    "description": "test",
    "isDefault": false
}

### Update
PUT http://localhost:8688/api/v1/schemes/11
Content-Type: application/json

{
  "description": "test",
  "isDefault": false,
  "updatedBy": 1
}

//"isDeleted": false,
//"createdAt": "2025-06-12T10:05:40.000+00:00",
//"updatedAt": "2025-06-12T10:05:39.000+00:00",
//"createdBy": 1,
PUT http://localhost:8688/api/v1/schemes/12
Content-Type: application/json

{
  "id": 12,
  "nameTag": "test",
  "description": "test",
  "isDefault": false
}

###
DELETE http://localhost:8688/api/v1/schemes/10
Content-Type: application/json


### CommissionRate
### List
GET http://localhost:8688/api/v1/commission-rates
Content-Type: application/json

{
  "id": 0,
  "rate": {},
  "description": "",
  "createdAt": {},
  "updatedAt": {},
  "createdBy": 0,
  "updatedBy": 0,
  "isDeleted": false
}


### Get
GET http://localhost:8688/api/v1/commission-rates/1
Content-Type: application/json

{
  "id": 0,
  "rate": {},
  "description": "",
  "createdAt": {},
  "updatedAt": {},
  "createdBy": 0,
  "updatedBy": 0,
  "isDeleted": false
}


### create
POST http://localhost:8688/api/v1/commission-rates
Content-Type: application/json

{
  "id": 31,
  "rate": 0.01,
  "description": "VIP1",
  "createdAt": 1717756800000,
  "updatedAt": 1717756800000,
  "createdBy": 1,
  "updatedBy": 1,
  "isDeleted": false
}

###
PUT http://localhost:8688/api/v1/commission-rates/38
Content-Type: application/json

{
  "id": 38,
  "rate": 0.01,
  "description": "VIP2",
  "createdAt": 1717756800000,
  "updatedAt": 1717756800000,
  "createdBy": 1,
  "updatedBy": 1,
  "isDeleted": false
}


### delete
DELETE http://localhost:8688/api/v1/commission-rates/38
Content-Type: application/json


### Company Commission Scheme
###
GET http://localhost:8688/api/v1/company-commission-schemes
Content-Type: application/json

{
  "id": 0,
  "moneyChangerId": {},
  "commissionRateId": {},
  "createdAt": {},
  "updatedAt": {},
  "createdBy": 0,
  "updatedBy": 0,
  "isDeleted": false
}

### get
GET http://localhost:8688/api/v1/company-commission-schemes/1
Content-Type: application/json

{
  "id": 0,
  "moneyChangerId": {},
  "commissionRateId": {},
  "createdAt": {},
  "updatedAt": {},
  "createdBy": 0,
  "updatedBy": 0,
  "isDeleted": false
}


### create
POST http://localhost:8688/api/v1/company-commission-schemes
Content-Type: application/json

{
  "id": 1,
  "moneyChanger": {
    "id": 11,
    "companyName": "Global Forex Pte Ltd",
    "email": "contact@globalforex.sg",
    "dateOfIncorporation": "2010-05-12",
    "address": "123 Orchard Road, #12-01, Singapore",
    "country": "Singapore",
    "postalCode": "238888",
    "notes": "Licensed since 2010. Strong compliance record.",
    "uen": "201012345K",
    "schemeId": 2,
    "createdAt": 1717756800000,
    "updatedAt": 1717756800000,
    "createdBy": 1,
    "updatedBy": 1,
    "isDeleted": false
  },
  "commissionRate": {
    "id": 40,
    "rate": 2.50,
    "description": "VIP Customer Rate",
    "createdAt": 1717756800000,
    "updatedAt": 1717756800000,
    "createdBy": 1,
    "updatedBy": 1,
    "isDeleted": false
  },
  "createdAt": 1717756800000,
  "updatedAt": 1717756800000,
  "createdBy": 1,
  "updatedBy": 1,
  "isDeleted": false
}

### Get
GET http://localhost:8688/api/actuator/health
Content-Type: application/json
